<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bg3HonourRecovery\Bg3HonourRecovery.csproj" />
    <Reference Include="LSLib">
      <HintPath>..\ThirdParty\LSLib\LSLib.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
